#[derive(Copy, Clone, Eq, PartialEq, Debug, Hash)]
/// Represents a state in the JTAG state machine
pub enum JTAGState {
    TestLogicReset,
    RunTestIdle,

    SelectDR,
    CaptureDR,
    ShiftDR,
    Exit1DR,
    PauseDR,
    Exit2DR,
    UpdateDR,

    SelectIR,
    CaptureIR,
    ShiftIR,
    Exit1IR,
    PauseIR,
    Exit2IR,
    UpdateIR,
}

impl JTAGState {
    /// Calculate the shortest path (via TMS transitions) to get to `end` from this state
    pub const fn path_to(self: &JTAGState, end: JTAGState) -> &'static [bool] {
        // Note: autogenerated with Python script jtag_fsm_compute.py
        match &self {
            JTAGState::TestLogicReset => match end {
                JTAGState::TestLogicReset => &[],
                JTAGState::RunTestIdle => &[false],
                JTAGState::SelectDR => &[false, true],
                JTAGState::CaptureDR => &[false, true, false],
                JTAGState::ShiftDR => &[false, true, false, false],
                JTAGState::Exit1DR => &[false, true, false, true],
                JTAGState::PauseDR => &[false, true, false, true, false],
                JTAGState::Exit2DR => &[false, true, false, true, false, true],
                JTAGState::UpdateDR => &[false, true, false, true, true],
                JTAGState::SelectIR => &[false, true, true],
                JTAGState::CaptureIR => &[false, true, true, false],
                JTAGState::ShiftIR => &[false, true, true, false, false],
                JTAGState::Exit1IR => &[false, true, true, false, true],
                JTAGState::PauseIR => &[false, true, true, false, true, false],
                JTAGState::Exit2IR => &[false, true, true, false, true, false, true],
                JTAGState::UpdateIR => &[false, true, true, false, true, true],
            },
            JTAGState::RunTestIdle => match end {
                JTAGState::TestLogicReset => &[true, true, true],
                JTAGState::RunTestIdle => &[],
                JTAGState::SelectDR => &[true],
                JTAGState::CaptureDR => &[true, false],
                JTAGState::ShiftDR => &[true, false, false],
                JTAGState::Exit1DR => &[true, false, true],
                JTAGState::PauseDR => &[true, false, true, false],
                JTAGState::Exit2DR => &[true, false, true, false, true],
                JTAGState::UpdateDR => &[true, false, true, true],
                JTAGState::SelectIR => &[true, true],
                JTAGState::CaptureIR => &[true, true, false],
                JTAGState::ShiftIR => &[true, true, false, false],
                JTAGState::Exit1IR => &[true, true, false, true],
                JTAGState::PauseIR => &[true, true, false, true, false],
                JTAGState::Exit2IR => &[true, true, false, true, false, true],
                JTAGState::UpdateIR => &[true, true, false, true, true],
            },
            JTAGState::SelectDR => match end {
                JTAGState::TestLogicReset => &[true, true],
                JTAGState::RunTestIdle => &[true, true, false],
                JTAGState::SelectDR => &[],
                JTAGState::CaptureDR => &[false],
                JTAGState::ShiftDR => &[false, false],
                JTAGState::Exit1DR => &[false, true],
                JTAGState::PauseDR => &[false, true, false],
                JTAGState::Exit2DR => &[false, true, false, true],
                JTAGState::UpdateDR => &[false, true, true],
                JTAGState::SelectIR => &[true],
                JTAGState::CaptureIR => &[true, false],
                JTAGState::ShiftIR => &[true, false, false],
                JTAGState::Exit1IR => &[true, false, true],
                JTAGState::PauseIR => &[true, false, true, false],
                JTAGState::Exit2IR => &[true, false, true, false, true],
                JTAGState::UpdateIR => &[true, false, true, true],
            },
            JTAGState::CaptureDR => match end {
                JTAGState::TestLogicReset => &[true, true, true, true, true],
                JTAGState::RunTestIdle => &[true, true, false],
                JTAGState::SelectDR => &[true, true, true],
                JTAGState::CaptureDR => &[],
                JTAGState::ShiftDR => &[false],
                JTAGState::Exit1DR => &[true],
                JTAGState::PauseDR => &[true, false],
                JTAGState::Exit2DR => &[true, false, true],
                JTAGState::UpdateDR => &[true, true],
                JTAGState::SelectIR => &[true, true, true, true],
                JTAGState::CaptureIR => &[true, true, true, true, false],
                JTAGState::ShiftIR => &[true, true, true, true, false, false],
                JTAGState::Exit1IR => &[true, true, true, true, false, true],
                JTAGState::PauseIR => &[true, true, true, true, false, true, false],
                JTAGState::Exit2IR => &[true, true, true, true, false, true, false, true],
                JTAGState::UpdateIR => &[true, true, true, true, false, true, true],
            },
            JTAGState::ShiftDR => match end {
                JTAGState::TestLogicReset => &[true, true, true, true, true],
                JTAGState::RunTestIdle => &[true, true, false],
                JTAGState::SelectDR => &[true, true, true],
                JTAGState::CaptureDR => &[true, true, true, false],
                JTAGState::ShiftDR => &[],
                JTAGState::Exit1DR => &[true],
                JTAGState::PauseDR => &[true, false],
                JTAGState::Exit2DR => &[true, false, true],
                JTAGState::UpdateDR => &[true, true],
                JTAGState::SelectIR => &[true, true, true, true],
                JTAGState::CaptureIR => &[true, true, true, true, false],
                JTAGState::ShiftIR => &[true, true, true, true, false, false],
                JTAGState::Exit1IR => &[true, true, true, true, false, true],
                JTAGState::PauseIR => &[true, true, true, true, false, true, false],
                JTAGState::Exit2IR => &[true, true, true, true, false, true, false, true],
                JTAGState::UpdateIR => &[true, true, true, true, false, true, true],
            },
            JTAGState::Exit1DR => match end {
                JTAGState::TestLogicReset => &[true, true, true, true],
                JTAGState::RunTestIdle => &[true, false],
                JTAGState::SelectDR => &[true, true],
                JTAGState::CaptureDR => &[true, true, false],
                JTAGState::ShiftDR => &[false, true, false],
                JTAGState::Exit1DR => &[],
                JTAGState::PauseDR => &[false],
                JTAGState::Exit2DR => &[false, true],
                JTAGState::UpdateDR => &[true],
                JTAGState::SelectIR => &[true, true, true],
                JTAGState::CaptureIR => &[true, true, true, false],
                JTAGState::ShiftIR => &[true, true, true, false, false],
                JTAGState::Exit1IR => &[true, true, true, false, true],
                JTAGState::PauseIR => &[true, true, true, false, true, false],
                JTAGState::Exit2IR => &[true, true, true, false, true, false, true],
                JTAGState::UpdateIR => &[true, true, true, false, true, true],
            },
            JTAGState::PauseDR => match end {
                JTAGState::TestLogicReset => &[true, true, true, true, true],
                JTAGState::RunTestIdle => &[true, true, false],
                JTAGState::SelectDR => &[true, true, true],
                JTAGState::CaptureDR => &[true, true, true, false],
                JTAGState::ShiftDR => &[true, false],
                JTAGState::Exit1DR => &[true, false, true],
                JTAGState::PauseDR => &[],
                JTAGState::Exit2DR => &[true],
                JTAGState::UpdateDR => &[true, true],
                JTAGState::SelectIR => &[true, true, true, true],
                JTAGState::CaptureIR => &[true, true, true, true, false],
                JTAGState::ShiftIR => &[true, true, true, true, false, false],
                JTAGState::Exit1IR => &[true, true, true, true, false, true],
                JTAGState::PauseIR => &[true, true, true, true, false, true, false],
                JTAGState::Exit2IR => &[true, true, true, true, false, true, false, true],
                JTAGState::UpdateIR => &[true, true, true, true, false, true, true],
            },
            JTAGState::Exit2DR => match end {
                JTAGState::TestLogicReset => &[true, true, true, true],
                JTAGState::RunTestIdle => &[true, false],
                JTAGState::SelectDR => &[true, true],
                JTAGState::CaptureDR => &[true, true, false],
                JTAGState::ShiftDR => &[false],
                JTAGState::Exit1DR => &[false, true],
                JTAGState::PauseDR => &[false, true, false],
                JTAGState::Exit2DR => &[],
                JTAGState::UpdateDR => &[true],
                JTAGState::SelectIR => &[true, true, true],
                JTAGState::CaptureIR => &[true, true, true, false],
                JTAGState::ShiftIR => &[true, true, true, false, false],
                JTAGState::Exit1IR => &[true, true, true, false, true],
                JTAGState::PauseIR => &[true, true, true, false, true, false],
                JTAGState::Exit2IR => &[true, true, true, false, true, false, true],
                JTAGState::UpdateIR => &[true, true, true, false, true, true],
            },
            JTAGState::UpdateDR => match end {
                JTAGState::TestLogicReset => &[true, true, true],
                JTAGState::RunTestIdle => &[false],
                JTAGState::SelectDR => &[true],
                JTAGState::CaptureDR => &[true, false],
                JTAGState::ShiftDR => &[true, false, false],
                JTAGState::Exit1DR => &[true, false, true],
                JTAGState::PauseDR => &[true, false, true, false],
                JTAGState::Exit2DR => &[true, false, true, false, true],
                JTAGState::UpdateDR => &[],
                JTAGState::SelectIR => &[true, true],
                JTAGState::CaptureIR => &[true, true, false],
                JTAGState::ShiftIR => &[true, true, false, false],
                JTAGState::Exit1IR => &[true, true, false, true],
                JTAGState::PauseIR => &[true, true, false, true, false],
                JTAGState::Exit2IR => &[true, true, false, true, false, true],
                JTAGState::UpdateIR => &[true, true, false, true, true],
            },
            JTAGState::SelectIR => match end {
                JTAGState::TestLogicReset => &[true],
                JTAGState::RunTestIdle => &[true, false],
                JTAGState::SelectDR => &[true, false, true],
                JTAGState::CaptureDR => &[true, false, true, false],
                JTAGState::ShiftDR => &[true, false, true, false, false],
                JTAGState::Exit1DR => &[true, false, true, false, true],
                JTAGState::PauseDR => &[true, false, true, false, true, false],
                JTAGState::Exit2DR => &[true, false, true, false, true, false, true],
                JTAGState::UpdateDR => &[true, false, true, false, true, true],
                JTAGState::SelectIR => &[],
                JTAGState::CaptureIR => &[false],
                JTAGState::ShiftIR => &[false, false],
                JTAGState::Exit1IR => &[false, true],
                JTAGState::PauseIR => &[false, true, false],
                JTAGState::Exit2IR => &[false, true, false, true],
                JTAGState::UpdateIR => &[false, true, true],
            },
            JTAGState::CaptureIR => match end {
                JTAGState::TestLogicReset => &[true, true, true, true, true],
                JTAGState::RunTestIdle => &[true, true, false],
                JTAGState::SelectDR => &[true, true, true],
                JTAGState::CaptureDR => &[true, true, true, false],
                JTAGState::ShiftDR => &[true, true, true, false, false],
                JTAGState::Exit1DR => &[true, true, true, false, true],
                JTAGState::PauseDR => &[true, true, true, false, true, false],
                JTAGState::Exit2DR => &[true, true, true, false, true, false, true],
                JTAGState::UpdateDR => &[true, true, true, false, true, true],
                JTAGState::SelectIR => &[true, true, true, true],
                JTAGState::CaptureIR => &[],
                JTAGState::ShiftIR => &[false],
                JTAGState::Exit1IR => &[true],
                JTAGState::PauseIR => &[true, false],
                JTAGState::Exit2IR => &[true, false, true],
                JTAGState::UpdateIR => &[true, true],
            },
            JTAGState::ShiftIR => match end {
                JTAGState::TestLogicReset => &[true, true, true, true, true],
                JTAGState::RunTestIdle => &[true, true, false],
                JTAGState::SelectDR => &[true, true, true],
                JTAGState::CaptureDR => &[true, true, true, false],
                JTAGState::ShiftDR => &[true, true, true, false, false],
                JTAGState::Exit1DR => &[true, true, true, false, true],
                JTAGState::PauseDR => &[true, true, true, false, true, false],
                JTAGState::Exit2DR => &[true, true, true, false, true, false, true],
                JTAGState::UpdateDR => &[true, true, true, false, true, true],
                JTAGState::SelectIR => &[true, true, true, true],
                JTAGState::CaptureIR => &[true, true, true, true, false],
                JTAGState::ShiftIR => &[],
                JTAGState::Exit1IR => &[true],
                JTAGState::PauseIR => &[true, false],
                JTAGState::Exit2IR => &[true, false, true],
                JTAGState::UpdateIR => &[true, true],
            },
            JTAGState::Exit1IR => match end {
                JTAGState::TestLogicReset => &[true, true, true, true],
                JTAGState::RunTestIdle => &[true, false],
                JTAGState::SelectDR => &[true, true],
                JTAGState::CaptureDR => &[true, true, false],
                JTAGState::ShiftDR => &[true, true, false, false],
                JTAGState::Exit1DR => &[true, true, false, true],
                JTAGState::PauseDR => &[true, true, false, true, false],
                JTAGState::Exit2DR => &[true, true, false, true, false, true],
                JTAGState::UpdateDR => &[true, true, false, true, true],
                JTAGState::SelectIR => &[true, true, true],
                JTAGState::CaptureIR => &[true, true, true, false],
                JTAGState::ShiftIR => &[false, true, false],
                JTAGState::Exit1IR => &[],
                JTAGState::PauseIR => &[false],
                JTAGState::Exit2IR => &[false, true],
                JTAGState::UpdateIR => &[true],
            },
            JTAGState::PauseIR => match end {
                JTAGState::TestLogicReset => &[true, true, true, true, true],
                JTAGState::RunTestIdle => &[true, true, false],
                JTAGState::SelectDR => &[true, true, true],
                JTAGState::CaptureDR => &[true, true, true, false],
                JTAGState::ShiftDR => &[true, true, true, false, false],
                JTAGState::Exit1DR => &[true, true, true, false, true],
                JTAGState::PauseDR => &[true, true, true, false, true, false],
                JTAGState::Exit2DR => &[true, true, true, false, true, false, true],
                JTAGState::UpdateDR => &[true, true, true, false, true, true],
                JTAGState::SelectIR => &[true, true, true, true],
                JTAGState::CaptureIR => &[true, true, true, true, false],
                JTAGState::ShiftIR => &[true, false],
                JTAGState::Exit1IR => &[true, false, true],
                JTAGState::PauseIR => &[],
                JTAGState::Exit2IR => &[true],
                JTAGState::UpdateIR => &[true, true],
            },
            JTAGState::Exit2IR => match end {
                JTAGState::TestLogicReset => &[true, true, true, true],
                JTAGState::RunTestIdle => &[true, false],
                JTAGState::SelectDR => &[true, true],
                JTAGState::CaptureDR => &[true, true, false],
                JTAGState::ShiftDR => &[true, true, false, false],
                JTAGState::Exit1DR => &[true, true, false, true],
                JTAGState::PauseDR => &[true, true, false, true, false],
                JTAGState::Exit2DR => &[true, true, false, true, false, true],
                JTAGState::UpdateDR => &[true, true, false, true, true],
                JTAGState::SelectIR => &[true, true, true],
                JTAGState::CaptureIR => &[true, true, true, false],
                JTAGState::ShiftIR => &[false],
                JTAGState::Exit1IR => &[false, true],
                JTAGState::PauseIR => &[false, true, false],
                JTAGState::Exit2IR => &[],
                JTAGState::UpdateIR => &[true],
            },
            JTAGState::UpdateIR => match end {
                JTAGState::TestLogicReset => &[true, true, true],
                JTAGState::RunTestIdle => &[false],
                JTAGState::SelectDR => &[true],
                JTAGState::CaptureDR => &[true, false],
                JTAGState::ShiftDR => &[true, false, false],
                JTAGState::Exit1DR => &[true, false, true],
                JTAGState::PauseDR => &[true, false, true, false],
                JTAGState::Exit2DR => &[true, false, true, false, true],
                JTAGState::UpdateDR => &[true, false, true, true],
                JTAGState::SelectIR => &[true, true],
                JTAGState::CaptureIR => &[true, true, false],
                JTAGState::ShiftIR => &[true, true, false, false],
                JTAGState::Exit1IR => &[true, true, false, true],
                JTAGState::PauseIR => &[true, true, false, true, false],
                JTAGState::Exit2IR => &[true, true, false, true, false, true],
                JTAGState::UpdateIR => &[],
            },
        }
    }

    /// Calculate the next state from this state with the given value on TMS
    pub const fn transition(self: &JTAGState, tms: bool) -> JTAGState {
        match &self {
            JTAGState::TestLogicReset => {
                if !tms {
                    JTAGState::RunTestIdle
                } else {
                    JTAGState::TestLogicReset
                }
            }
            JTAGState::RunTestIdle => {
                if !tms {
                    JTAGState::RunTestIdle
                } else {
                    JTAGState::SelectDR
                }
            }

            JTAGState::SelectDR => {
                if !tms {
                    JTAGState::CaptureDR
                } else {
                    JTAGState::SelectIR
                }
            }
            JTAGState::CaptureDR => {
                if !tms {
                    JTAGState::ShiftDR
                } else {
                    JTAGState::Exit1DR
                }
            }
            JTAGState::ShiftDR => {
                if !tms {
                    JTAGState::ShiftDR
                } else {
                    JTAGState::Exit1DR
                }
            }
            JTAGState::Exit1DR => {
                if !tms {
                    JTAGState::PauseDR
                } else {
                    JTAGState::UpdateDR
                }
            }
            JTAGState::PauseDR => {
                if !tms {
                    JTAGState::PauseDR
                } else {
                    JTAGState::Exit2DR
                }
            }
            JTAGState::Exit2DR => {
                if !tms {
                    JTAGState::ShiftDR
                } else {
                    JTAGState::UpdateDR
                }
            }
            JTAGState::UpdateDR => {
                if !tms {
                    JTAGState::RunTestIdle
                } else {
                    JTAGState::SelectDR
                }
            }

            JTAGState::SelectIR => {
                if !tms {
                    JTAGState::CaptureIR
                } else {
                    JTAGState::TestLogicReset
                }
            }
            JTAGState::CaptureIR => {
                if !tms {
                    JTAGState::ShiftIR
                } else {
                    JTAGState::Exit1IR
                }
            }
            JTAGState::ShiftIR => {
                if !tms {
                    JTAGState::ShiftIR
                } else {
                    JTAGState::Exit1IR
                }
            }
            JTAGState::Exit1IR => {
                if !tms {
                    JTAGState::PauseIR
                } else {
                    JTAGState::UpdateIR
                }
            }
            JTAGState::PauseIR => {
                if !tms {
                    JTAGState::PauseIR
                } else {
                    JTAGState::Exit2IR
                }
            }
            JTAGState::Exit2IR => {
                if !tms {
                    JTAGState::ShiftIR
                } else {
                    JTAGState::UpdateIR
                }
            }
            JTAGState::UpdateIR => {
                if !tms {
                    JTAGState::RunTestIdle
                } else {
                    JTAGState::SelectDR
                }
            }
        }
    }
}

#[cfg(test)]
mod tests {
    use crate::JTAGState;

    #[test]
    fn test_fsm_transitions() {
        for state_a in [
            JTAGState::TestLogicReset,
            JTAGState::RunTestIdle,
            JTAGState::SelectDR,
            JTAGState::CaptureDR,
            JTAGState::ShiftDR,
            JTAGState::Exit1DR,
            JTAGState::PauseDR,
            JTAGState::Exit2DR,
            JTAGState::UpdateDR,
            JTAGState::SelectIR,
            JTAGState::CaptureIR,
            JTAGState::ShiftIR,
            JTAGState::Exit1IR,
            JTAGState::PauseIR,
            JTAGState::Exit2IR,
            JTAGState::UpdateIR,
        ] {
            for state_b in [
                JTAGState::TestLogicReset,
                JTAGState::RunTestIdle,
                JTAGState::SelectDR,
                JTAGState::CaptureDR,
                JTAGState::ShiftDR,
                JTAGState::Exit1DR,
                JTAGState::PauseDR,
                JTAGState::Exit2DR,
                JTAGState::UpdateDR,
                JTAGState::SelectIR,
                JTAGState::CaptureIR,
                JTAGState::ShiftIR,
                JTAGState::Exit1IR,
                JTAGState::PauseIR,
                JTAGState::Exit2IR,
                JTAGState::UpdateIR,
            ] {
                let path = state_a.path_to(state_b);

                let mut state = state_a;
                for &tms in path {
                    state = state.transition(tms);
                }
                assert_eq!(state, state_b);
            }
        }
    }
}
